//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public string Store { get; set; }
        public string StoreAddress { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
